version: '3'

volumes:
  redis_data:
    driver: local
  app_bundle:
    driver: local

services:
  redis:
    image: redis:5-alpine
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --appendonly yes
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - app
    ports:
      - 80:80

  app:
    image: danjenuil/lcbo-api
    depends_on:
      - redis
    volumes:
      - /Users/dannyjenuil/Desktop/test_log:/lcboapi/log
    env_file: .env
