default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 10

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *default
  database: lcboapi_production
  host: <%= ENV['POSTGRES_RDS_ENDPOINT'] %>
  user: <%= ENV['POSTGRES_RDS_USER'] %>
  password: <%= ENV['POSTGRES_RDS_PASSWORD'] %>

